services:
  queue:
    image: rabbitmq:4.1.0
    ports:
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  database:
    image: postgres:17.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

  script:
    build:
      context: ./
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: ${DB_PASS}
      QUEUE_HOST: queue
      QUEUE_NAME: "wiki-links"
    volumes:
      - data:/app/data:z
    depends_on:
      database:
        condition: "service_healthy"
      queue:
        condition: "service_healthy"

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
